language: node_js
node_js:
- '6'
sudo: false
install:
- npm install
- npm install -g browserify
- wget https://releases.hashicorp.com/terraform/0.6.16/terraform_0.6.16_linux_amd64.zip
- unzip terraform_0.6.16_linux_amd64.zip -d terraform
- export PATH=$PATH:$PWD/terraform
script: make test
env:
  secure: rgrSwdvTdfuVvf7A5b3SYP49t600wxI8UUy7HZyGUNp5/LQFuO/MsXsM6hiIsumXhtI/yU6vjWGhELzL3Jvac4ey/jFurf2Jfkok/9JffeOefiHYO+uOVcll2CcDhPjdeO/QBbOVHASLKDin9XZcFXf79hhDY8h8ql9C/y+z0ANKJ45Fj7CAWHMhi7XCEd5vorfRgCw6g0YXaprAF1P8WOnfjUC8kYwvcJ18BWXKHar1565b6IABBQ6QY9NGxdJgTKQNTIa0yxs0NupTkYcYn+QIHl3X3n06GhspwJj/B8QDqOTz2ZENmrNqb5nW09NPKV12ATkaBdtp4USZG3MzrmK1pk9Y8wePrrNU6sGYnaISwXGmW7myCoq/f7RRljFhXiC5t3CHeSDnW7hevx6DHWL/4EPJAHtuFb0c84LLqeau+GeomPxBz4LC6XDC7FMRhdRVPx5QB5nbQ4xH9jO8Ph5RA87uQARuK3H+eyONVIXsgFAeLa7N9bimpuOOCAMPBWXsWTjAyz2fgpQA1MKl3HEP0wVm9JEXfHRwdldHMv5YHPXFwnQj2Ihbek/IAu6iVDgQ2KgI/bOG8lUXXEpKQViCGjn04/6zDtx2bFkYOvik1/9/zHfTFPXGZbcx/bn/erpE8lkFfpNCYNRAQFxMcGGLdEAz1VG2e0nFbbukqLY=
