language: node_js
node_js:
- '6'
sudo: false
install:
- npm install
- npm install -g browserify
- wget https://releases.hashicorp.com/terraform/0.6.16/terraform_0.6.16_linux_amd64.zip
- unzip terraform_0.6.16_linux_amd64.zip -d terraform
- export PATH=$PATH:$PWD/terraform
script: make test
env:
  secure: B+uMwEdFlVsH+F9VAfzd0v59AuY5RyJlPcPjGETtUYzyIZHdWzfQkEqmiKF4djShlp1MadFToRzHeNKAULocj360krcMu+YT9er/dg73NLjk5/ZliuHuI5I1p4aaTmV6J8Acp04Rfpf/pAtY1/RjMRhzXRUpEfAnG+pfrRFFVpV86iUIu/lhf1FKqtJbc2zg9DuM8kaJ6Ok4Gs+4bA3y3iolC3gEHSg/SaW/2SZyCnbPgu/wr0JwNXjS1q9mqzjCHj00NXvXAfwxJ1LPFETebBu//fnEN6AERkWPdW7K2KIZB6QfGVD+Us3LU1nEn/J+FMBSoX2U6fRMqjEZaAQ8fcgsxqK+XZmI5mULTyrLZG0wY4OeP+S1nKGx0l/LJXhzSwd1dIob+svWsUu3xVL/sdL9n77Pe0CPcfm7OXWT7XMZQhFZSWuVb5GlJXs3QgGprveLdTlD8GEwjId8xvWBLYVgn965FOFzO9+K6M2V1HrkpQN0i7rLc1pqYFbz49Vbdar1PXUv5S0x+lWnIFLpqKE5Uv/flwxv1fQM4iG8svUT5KgNDcbOrboxymmfikovNoHER+RIGtk5v9BEumH4VUCshvpUPl1bWOLesC9LApChHA7JmrMWnaw9f9pa/nDiI2CtoICY3GJndJx3l9N6z7eGY8yKysSz3r/mTfESPfs=
