language: node_js
node_js:
- '6'
sudo: false
install:
- npm install
- npm install -g browserify
- wget https://releases.hashicorp.com/terraform/0.6.16/terraform_0.6.16_linux_amd64.zip
- unzip terraform_0.6.16_linux_amd64.zip -d terraform
- export PATH=$PATH:$PWD/terraform
script: make test
env:
  secure: RV49zMZhBdkgCoamWmMvtLO6tmUpuhx+s6s7+5d5FtEiAd3SbuM9JRzBLnyVc0EtweQSXXWCIzIUkGyuIu/AFL2JhYgN0IisEbu2s8j8jkQ/iHSPAtG/yTs07BGTHAJSPCsoYHkMQMhW9hIYbKZTAvEMa9guowgcL5lUG/yt5ahhiBdMEJR00OaQUY3k5TU8vM4CXty72dEtaCJIPBWLGf5EBt5x92euVrt3O1pm3ViJNjTs+u/3v5b94CW28ruSCrDejyXxZZIbg27UboXgxeVkTbtApojqvKGlZXfzjI9heGivir9qNHK/j9JxqfCL4phclG6AihckyDY+Zw9tPSkeexqeYs+H44AUx8hrvtu8nxQsXSLMnxGReBMGrRuQLyMEJa8vUW5X6ff3Si21nlf7ZQ7kAWCcAaXnBysLEqFgEU6SszHyCoez/KYFPVOHSiIH6MaRoOEAhwx0DaqmpibAX15YA/3NQEgcxLw5TbH7yHcmRlWkNzYK8jxlWFTorf4ps5juWBXPrVVYgY7gUpNoInJwdM86A8u7O2xyEE+IbtDjHkYAWhLsI9CKk/8WNNOxgBBXm/uXUTdqIgYwElqIq4lFiWoAhr9J8qAmWC+RnekdJq3cnbtoJs8r0MrZfmLT127DP0ehu9KDPAs6ppIfBRQxcIm/XlLMZewc+OM=
  - AWS_REGION=us-west-2
